### ISSUE TITLE
OAuthToken has no Dictionary decoder

### ISSUE THREAD

**Issue by gkoep** [vakoc/particle-swift#1]
Trying to build from your usage example:
... 
class MyParticleCloud {
    
    var token: OAuthToken?
    var particleCloud: ParticleCloud?
    
    init() {
        if let dictionary = UserDefaults.standard.value(forKey: "token") as? Dictionary<String,Any> {
            self.token = OAuthToken(with: dictionary)
        }
        particleCloud = ParticleCloud(secureStorage: self)
    }
 ...
    func updateOAuthToken(_ token: OAuthToken?, forRealm realm: String) {
        self.token = token
        //Persist this for subsequent runs
        UserDefaults.standard.set(**token.dictionary**, forKey: "token")
    }
...

OAuthToken has no decoder for Dictionary as  specified in the Authentication.swift release I've recently pulled down:
...
public struct OAuthToken: Codable {
    
    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case refreshToken = "refresh_token"
        case created
    }
    
    /// the magical token you will use for all other requests
    public var accessToken: String
    
    /// the token type, e.g. bearer
    public var tokenType: String
    
    /// the number of seconds this token is valid for.  0 means forever
    public var expiresIn: TimeInterval
    
    /// used to generate a new access token when it has expired
    public var refreshToken: String
    
    /// the time the structure was created
    public let created = Date()

    /// The date the token expires
    public var expirationDate: Date {
        return self.created.addingTimeInterval(expiresIn)
    }
}
...
Sorry in advance if I'm overlooking something. Either it's "I'm not expert in Swift... yet!" or "I may not be working with the correct version release(s)"

**Comment by vakoc** [comment]
The sample code provided became obsolete with changes made to support Swift 4.  I have updated the sample code to correctly work the current source.

Thanks for the report.
