### ISSUE TITLE
Having trouble getting this working in iOS Project

### ISSUE THREAD

**Issue by sdevo619** [vakoc/particle-swift#2]
I have read your instructions multiple times now, but am really struggling to figure out how to get this working in an Xcode iOS and Watch OS project, and with Particle still not offering support for watch OS, I find myself here. I am currently using the Particle-SDK and Particle Setup SDK, through cocoa pods in my project file, and they are working fine, as long as I don't add a Watch OS target to the project file. As such, using SPM seems like a better route if I can actually get it to work. I don't mind creating a new project file if necessary either. I am developing a product with Particle Hardware, and know how to use coaopods no problem, but have zero experience with SPM, and can't seem to find any good tutorials. I'd really like to be able to use both cocoapods and SPM. SPM for as many things as possible, but cocoa pods for whatever I can't get working with SPM. Any chance of getting some step by step instructions or a video, detailing how to accomplish this with particle-swift?? Pretty please!!! Thank you very much in advance.

**Comment by vakoc** [comment]
I have added a sample project in the Examples directory that provides an iOS application that uses particle-swift to create a table view of devices
